
name: Build Test
on:
  push:
  pull_request:

jobs:
  test:
    name: "Running build test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js "14.x"
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
